/*
auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react'
import { useGLTFLoader } from '@react-three/drei/loaders/useGLTFLoader'
import { GLTF } from 'three/examples/jsm/loaders/GLTFLoader'

type GLTFResult = GLTF & {
  nodes: {
    ['Cube.001_0']: THREE.Mesh
    ['Cube.001_1']: THREE.Mesh
    Cube001: THREE.Mesh
    Cube002: THREE.Mesh
    ['Cube.004_0']: THREE.Mesh
    ['Cube.004_1']: THREE.Mesh
    ['Cube.004_2']: THREE.Mesh
    Sphere_0: THREE.Mesh
    Sphere_1: THREE.Mesh
  }
  materials: {
    CLAY_MODULE_CAMIR: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.003']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.001']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.004']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.005']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.006']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.007']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.008']: THREE.MeshStandardMaterial
    ['CLAY_MODULE_CAMIR.009']: THREE.MeshStandardMaterial
  }
}

export default function Model(props: JSX.IntrinsicElements['group']) {
  const group = useRef<THREE.Group>()
  const { nodes, materials } = useGLTFLoader<GLTFResult>('/ArmLidar.glb', true)
  return (
    <group ref={group} {...props} dispose={null}>
      <group position={[-0.02, 1.47, 0]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0.03, 0.05]}>
        <mesh material={materials.CLAY_MODULE_CAMIR} geometry={nodes['Cube.001_0'].geometry} />
        <mesh material={materials['CLAY_MODULE_CAMIR.003']} geometry={nodes['Cube.001_1'].geometry} />
      </group>
      <mesh
        material={materials['CLAY_MODULE_CAMIR.001']}
        geometry={nodes.Cube001.geometry}
        position={[-0.02, 1.45, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 0, 0.01]}
      />
      <mesh
        material={materials['CLAY_MODULE_CAMIR.004']}
        geometry={nodes.Cube002.geometry}
        position={[-0.02, 1.45, 0]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.01, 0, 0.01]}
      />
      <group position={[-0.02, 1.44, 0.06]} rotation={[0, 0, -Math.PI / 2]} scale={[0.01, 0, 0.09]}>
        <mesh material={materials['CLAY_MODULE_CAMIR.005']} geometry={nodes['Cube.004_0'].geometry} />
        <mesh material={materials['CLAY_MODULE_CAMIR.006']} geometry={nodes['Cube.004_1'].geometry} />
        <mesh material={materials['CLAY_MODULE_CAMIR.007']} geometry={nodes['Cube.004_2'].geometry} />
      </group>
      <group position={[-0.02, 1.68, 0.12]} rotation={[-0.56, 0, -Math.PI]} scale={[0.01, 0.01, 0.01]}>
        <mesh material={materials['CLAY_MODULE_CAMIR.008']} geometry={nodes.Sphere_0.geometry} />
        <mesh material={materials['CLAY_MODULE_CAMIR.009']} geometry={nodes.Sphere_1.geometry} />
      </group>
    </group>
  )
}
